spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/pedidos
    username: pedidos
    password: pedidos
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
